
name: Build App

on:
  push:
      tags:
        - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get dependencies
        run: flutter pub get
      - name: Build apk
        run: flutter build apk
      - name: Set env
        run: echo "RELEASE_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${RELEASE_NAME}
          tag_name: ${{ github.ref }}
          prerelease: true
          generate_release_notes: true
          files: |
            build/app/outputs/flutter-apk/app-release.apk
